name: Automatically fast forward merge repositories

# when the workflow is triggered
on:
  workflow_dispatch: # run this workflow manually
  schedule:
    - cron: '0 2 * * *' # * every day at 02:00

# * create 1 job for every repository
jobs:
  federdaemn_2_1-ublue-merkuros:
    name: Fast forward merge federdaemn/2.1-ublue-merkuros
    runs-on: ubuntu-latest
    env:
      REPOSITORY: federdaemn/2.1-ublue-merkuros
      ORIGIN: origin
      UPSTREAM: upstream
      BRANCH: template
      PATH_REPO: federdaemn_2_1-ublue-merkuros
      UPSTREAM_URL: https://github.com/ublue-os/startingpoint.git

    # steps to perform
    steps:
      - name: checkout needed repository
        uses: actions/checkout@v3
        with:
          # * repository
          repository: '${{ env.REPOSITORY }}'
          # * branch
          ref: '${{ env.BRANCH }}'
          # * path under $GITHUB_WORKSPACE
          path: '${{ env.PATH_REPO }}'
          # * token to access the repository
          token: '${{ secrets.GIT_FF_REPOSITORIES_TOKEN }}'
        
      - name: Only do a fast-forward merge with upstream!
        run: |
          # go to the repository/directory
          cd $GITHUB_WORKSPACE/$PATH_REPO
          # add the upstream repository
          git remote add upstream $UPSTREAM_URL
          # merge template branch
          git pull --ff-only $UPSTREAM $BRANCH


      - name: push the merged branch
        if: github.event_name != 'pull_request'
        run: |
          cd $GITHUB_WORKSPACE/$PATH_REPO
          git push $ORIGIN $BRANCH
